return {
  -- "yetone/avante.nvim",
  -- event = "VeryLazy",
  -- lazy = false,
  -- version = false,
  -- opts = {},
  -- build = "make",
  -- dependencies = {
  --   "stevearc/dressing.nvim",
  --   "nvim-lua/plenary.nvim",
  --   "MunifTanjim/nui.nvim",
  --   "nvim-tree/nvim-web-devicons", -- or echasnovski/mini.icons
  --   "github/copilot.vim",
  --   -- "zbirenbaum/copilot.lua", -- for providers='copilot'
  --   {
  --     "HakonHarnes/img-clip.nvim",
  --     event = "VeryLazy",
  --     opts = {
  --       default = {
  --         embed_image_as_base64 = false,
  --         prompt_for_file_name = false,
  --         drag_and_drop = {
  --           insert_mode = true,
  --         },
  --       },
  --     },
  --   },
  --   {
  --     "MeanderingProgrammer/render-markdown.nvim",
  --     opts = {
  --       file_types = { "markdown", "Avante" },
  --     },
  --     ft = { "markdown", "Avante" },
  --   },
  -- },
  -- config = function()
  --   local avante = require("avante")
  --   local avante_lib = require("avante_lib")
  --   require("img-clip").setup({})
  --   require("copilot").setup({})
  --   require("render-markdown").setup({})
  --
  --   avante_lib.load()
  --
  --   avante.setup({
  --     provider = "copilot",
  --     auto_suggestions_provider = "copilot",
  --     copilot = {
  --       endpoint = "https://api.github.com",
  --       model = "preview-o1",
  --       temperature = 0,
  --       max_tokens = 4096,
  --     },
  --     -- openai = {
  --     --   model = "o1-preview",
  --     --   temperature = 0.7,
  --     --   max_tokens = 1000,
  --     -- },
  --     -- claude = {
  --     --   endpoint = "https://api.anthropic.com",
  --     --   model = "claude-3-5-sonnet-20241022",
  --     --   temperature = 0,
  --     --   max_tokens = 4096,
  --     -- },
  --     behaviour = {
  --       auto_suggestions = false, -- Experimental stage
  --       auto_set_highlight_group = true,
  --       auto_set_keymaps = true,
  --       auto_apply_diff_after_generation = false,
  --       support_paste_from_clipboard = false,
  --       minimize_diff = true, -- Whether to remove unchanged lines when applying a code block
  --     },
  --     keymaps = {
  --       toggle_auto_suggestions = "<leader>as",
  --       accept_suggestion = "<leader>aa",
  --       next_suggestion = "<leader>an",
  --       previous_suggestion = "<leader>ap",
  --     },
  --   })
  -- end,
}
